### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by EnderDev** [simbo1905/thinbus-srp-npm#12]
Hello!

Your SDP implementation was the only decent one I could find out of the 10 or so Node.js implementations, and I wanted to know whether this project is still being maintained.

I'm interested in using SDP for a project so it would be great if I knew if this was still being maintained before using this.

Thanks.

**Comment by bufistov** [comment]
Hi,

We built a typescript version of SRP6a using this implementation as a baseline. You might want to check it out:
https://github.com/midonet/tssrp6a

**Comment by EnderDev** [comment]
Interesting, would your SRP6a implementation be good for use in production?

**Comment by bufistov** [comment]
Yes, of course! We used it internally for few years.

**Comment by EnderDev** [comment]
Has it been verified by security auditors. I just want to make sure that this is secure and is good to use.

**Comment by bufistov** [comment]
We did not do any formal verifications, it is just my word :) I think the random generator and hash functions are crypto secure, they come from some google project if I remember correctly.

**Comment by simbo1905** [comment]
Hey sorry, 

I missed this thread. 

This project aims to follow RFC 5054 and RFC 2945 and be compatible with Nimbus SPR. As those two RFCs won't change, there won't be any significant changes to the math or crypto of this package. This project has pluggable hashing and prime size to make it future-proof. As hardware gets faster, people can test much larger primes and use more robust hashing. 

The main challenge when this project had its most releases around 2014 - 2017 was poor support in both browsers and NodeJS support for strong random numbers and hashing. Packaging up polyfills and the like was a hassle and led to a lot of weight. Also, all the different ways to package up components in the JS world were confusing to me. IMHO, it is not the math but the dependencies/module layout/packaging/API that can be simplified. 

If we created a 2.0 version that required WebCrypto and NodeJS 15+ we can be polyfill free. I would still want it to be compatible with the Java implementation as that is which is well-studied, so maintaining compatibility gives some reassurance that the crypto is correct. There are some hassles around how the internal bytes of a BigDecimal number are taken as bytes and fed into the hash algorithms so that the Java version can be invoked. I can probably get that to have automated testing on GraalVM with NodeJS for java-2-js in memory tests.

I will close this for now and if I get some time between employments I might have a crack at a 2.0.
